version: "3.5"
services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - backend
    environment:
      - POSTGRES_MULTIPLE_DATABASES="${DB_NAME_1}","${DB_NAME_2}"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=""
    volumes:
      - ./logs/db:/logs
      - ./shell_scripts/:/docker-entrypoint-initdb.d
    command: postgres -c log_statement=all -c logging_collector=on  -c log_destination=stderr -c log_directory=/logs
networks:
  backend:
    name: ${NETWORK_NAME}
    driver: bridge
